# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - SentimentPredict

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './API' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.10' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/venv
          source ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/venv/bin/activate

      - name: Install dependencies
        run: |                     
          source ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/venv/bin/activate     
          pip install -r ./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt
      
      - name: Run tests
        run: |
          source ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/venv/bin/activate
          python ./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/test_api.py


      - name: Zip artifact for deployment
        run: zip release.zip ./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip     
        
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'SentimentPredict'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F6F9C32038464DFAAE612264DAF37E6A }}
          sku: 'flexconsumption'
          remote-build: 'true'