name: Build and deploy Python project to Azure Function App - Projet-Analyse-Sentiment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'

  AZURE_FUNCTIONAPP_ROOT_FOLDER: 'API'
  MLFLOW_RUNS_DIR: 'Modélisation/mlruns'
  MODEL_EXPERIMENT_ID: '604306899295521234'
  MODEL_RUN_ID: 'b72ca14fe64c4a549306aebe1ba4641c' 
  ARTIFACT_ZIP_NAME: 'python-app.zip'
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=ea4ee31a-3f2a-4700-a97a-9bf7927331e1;IngestionEndpoint=https://francecentral-1.in.applicationinsights.azure.com/;LiveEndpoint=https://francecentral.livediagnostics.monitor.azure.com/;ApplicationId=b9d6be7f-78af-4da6-9bbe-6281ab85d1aa"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment (optional for GH Actions, but good for local consistency)
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies for the Function App
        run: pip install -r ${{ env.AZURE_FUNCTIONAPP_ROOT_FOLDER }}/requirements.txt

      - name: Create model directory in Function App folder
        run: mkdir -p ${{ env.AZURE_FUNCTIONAPP_ROOT_FOLDER }}/model

      - name: Run tests
        working-directory: ./${{ env.AZURE_FUNCTIONAPP_ROOT_FOLDER }}
        run: |
          pip install pytest # or other test runners
          pytest

      - name: Zip artifact for deployment (Function App folder contents)
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_ROOT_FOLDER }}
          zip -r ../${{ env.ARTIFACT_ZIP_NAME }} . -x "*venv/*" -x "*.git/*" -x "*__pycache__/*"
          # The '..' means the zip file is created in the repository root.

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app-artifact 
          path: ${{ env.ARTIFACT_ZIP_NAME }} 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: 'Production'
      url: ${{ steps.deploy-to-function.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app-artifact 


      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1.3.1
        id: deploy-to-function
        with:
          app-name: 'Projet-Analyse-Sentiment' 
          slot-name: 'Production' 
          package: ${{ env.ARTIFACT_ZIP_NAME }} 
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_18963F46B19E49D5A57355029EB94F04 }}
